### ISSUE TITLE
WebM files export as .png files

### ISSUE THREAD

**Issue by megahead11** [kakaroto/R20Exporter#14]
Downloading a campaign as a .zip seems to export all registered .webm files as .png files. The files don't seem to be converted completely, as renaming the .png s back to .webm causes them to work properly.

**Comment by kakaroto** [comment]
The exporter will save the files as `.png` regardless of the actual file format, since any file viewer should be able to detect the actual format of the file from its data. The `.png` extension is just a way to have a reliable/predictable filename for each file, and changing it would break the converter at this time. It's a valid issue though that it should not rename the original filename's extension, it's just unfortunately a more complicated fix than it would appear.
