### ISSUE TITLE
Exporter gets stuck at jukebox step

### ISSUE THREAD

**Issue by rouby44** [kakaroto/R20Exporter#16]
Each time I have tried to run the exporter (using the Chrome extension), it stops working at the "Saving Jukebox audio" step. The log simply says "couldn't download Jukebox audio from url: https://app.roll20.net/audio_library/play/[number strings]"

**Comment by Parotan** [comment]
i have the same issue.

**Comment by Nuku** [comment]
![image](https://user-images.githubusercontent.com/886729/85471919-fed64100-b565-11ea-88e8-5aedf1bbd4ed.png)

**Comment by SamF111** [comment]
Just chiming in to say that it's still an issue, is there a way around it?

**Comment by Hydrall** [comment]
Also having the same issue. It varies how many operations get stuck in progress, but nevertheless it seems like a few songs just refuse to transfer. No errors in Chrome's console, though, at least that I can see.
![image](https://user-images.githubusercontent.com/14931056/89907047-276bd600-dbba-11ea-903d-fca5ae942ccd.png)

**Comment by LyricalStreetPoet** [comment]
I have the same issue.  Going to delete my entries and see if that helps...

**Comment by SamF111** [comment]
> I have the same issue. Going to delete my entries and see if that helps...

I overcame it by using a fork of this project (the one referenced here https://github.com/kakaroto/R20Exporter/issues/17)
> https://github.com/kyleady/R20Exporter/tree/0a420349b8daec3003c3b578065e76fbfe70e9b6

You have to manually import the extension to chrome if you do it this way.

**Comment by GregHuey** [comment]
I am having exactly this problem again, and I just freshly-installed v0.8.0
The exponential-backoff fix was supposed to be standard in v0.8.0, no?
The campaign I am trying to export is super, super big - it takes something like 6-8 hours to get to the jukebox stage, but I have tried it twice now, and it locks up at the same place.

UPDATE:
I tried do download the same game to a zip file on a machine with double the memory (32GB instead of 16GB) and it worked. The resulting zip file was slightly under 10GB. The download also took much less time (1-2 hours instead of 8-10) to get to the spot where the lockup had previously occurred. So, perhaps it was locking up due to running out of memory. Still, it would really, really help alot if the user got an **error message** instead of just a lockup. It is not only hard to diagnose the cause of a lockup, its also harder to even know if the download will complete (since its already running slowly, it is not immediately clear if there even is a lockup).

**Comment by kakaroto** [comment]
> I am having exactly this problem again, and I just freshly-installed v0.8.0 The exponential-backoff fix was supposed to be standard in v0.8.0, no? The campaign I am trying to export is super, super big - it takes something like 6-8 hours to get to the jukebox stage, but I have tried it twice now, and it locks up at the same place.
> 
> UPDATE: I tried do download the same game to a zip file on a machine with double the memory (32GB instead of 16GB) and it worked. The resulting zip file was slightly under 10GB. The download also took much less time (1-2 hours instead of 8-10) to get to the spot where the lockup had previously occurred. So, perhaps it was locking up due to running out of memory. Still, it would really, really help alot if the user got an **error message** instead of just a lockup. It is not only hard to diagnose the cause of a lockup, its also harder to even know if the download will complete (since its already running slowly, it is not immediately clear if there even is a lockup).

Unfortunately, lock ups like that are kind of hard to predict and take into account, the exporter does a "download this" and waits for it to finish, it can take 10 seconds to finish or an hour, it can't really know. There are timeouts in place but sometimes they misbehave (from either Chrome itself or from Roll20).
The RAM size making it faster could be related and running out of RAM made it slower as it used your hard drive as a temporary ram (swapping) or it could be that the network was simply faster at that moment.
From my experience when it freezes on the jukebox, it's a roll20 issue and it generally works if you try a few hours later.

**Comment by kakaroto** [comment]
I believe I've finally found the cause of these and fixed it with the  latest release.
Please re-open if you still encounter the issue.
Thanks

**Comment by PrimeSZero** [comment]
![export stuck](https://github.com/kakaroto/R20Exporter/assets/138145024/b0206709-1788-44e7-9c15-34330351c870)
Also getting stuck on the latest version. Error couldn't download jukebox audio from url and it just freezes forever on this step with no way to download the zip.
