### ISSUE TITLE
Getting stuck at "Saving Characters" 

### ISSUE THREAD

**Issue by hotlikepancakes** [kakaroto/R20Exporter#34]
Not sure if I'm really getting anywhere with the .zip export feature. I seem to be getting stuck at the saving characters part. I've turned off all of my extensions that would normally interact with Roll20, I've refreshed the page and even closed the browser completely a couple times causing it to get me to start over. I've tried looking through this support page for anything like what I've got going on, but anything close seems to have been resolved ages ago. Maybe this is something new, or maybe I'm missing something. (I'm not very clever with these kind of things, just trying to do my best to follow along with the directions where I can)

![image](https://user-images.githubusercontent.com/127643861/224524862-f31605a9-20be-427d-bc67-6d43f3c002f2.png)

-----------

![image](https://user-images.githubusercontent.com/127643861/224524876-9e6f57e0-92d8-450d-a66a-4c2633318b4d.png)

**Comment by kakaroto** [comment]
Humm.. that's peculiar. You can see that you have 528 characters,  and Roll20 seems to get stuck at loading them after 154. I'm not sure why. You can see the "Waited 30 seconds with no progress. Assuming Roll 20 is being weird" messages in the logs.
My guess is that perhaps you're clicking the button to export too quickly after loading into the game, perhaps let it rest for a minute or so before, just so Roll20 can do its thing. I'm not sure if that would fix anything though as it seems that it's just failing to load some character sheets. I would assume if you could find those sheets and you opened them, Roll20 itself would get stuck on "Please wait..." while it tries to load the character sheet data.
I'm unsure how you could proceed further.
Are you logged in as a DM in the campaign or a player? This might be the kind of unexpected behavior you'd see if you're trying to export a campaign in which you're a player. Apart from that, I don't know.

**Comment by hotlikepancakes** [comment]
Interesting, so I'll give it some more time and see how it goes. I am the DM, that's why I was thinking I might have been doing something wrong. I was bale to get the .json file to work fine. But I thought there was a difference in the full scope of what's actually saved. I thought only the campaign with the .json, and everything from character sheets to chat log with the .zip

**Comment by kakaroto** [comment]
Btw, I just had a similar issue but it was when exporting the chat archive. Turns out, Roll20 was just having issues, and after something like 15 minutes, the exporter eventually timed out and finished its thing.
I was basically getting this when trying to access those same urls manually:
![image](https://user-images.githubusercontent.com/27990/225128804-7592ac7b-4168-4d71-96a0-e2fcca1fbdf4.png)

Note that I had this on the json export. The difference between json and zip is that the zip contains all your assets, so if you want to convert it to Foundry offline, or do multiple conversions tweaking various settings, it's best to use the zip, otherwise, you can use the json file to do the same thing, but the converter will download all those assets during conversion instead of during the export process.
Using json though doesn't allow to convert the playlists because the music files can't be downloaded from the tool, as you need to be authenticated to access it.

**Comment by kakaroto** [comment]
I just released 0.9.1 which added support for a few different ways to timeout stuck operations like that. Can you try again and confirm it's working without that issue now?
Thanks!
