### ISSUE TITLE
No Export Button Or Manual Export

### ISSUE THREAD

**Issue by CeGyger92** [kakaroto/R20Exporter#40]
The extension is installed but no button appears under settings. I looked at an old issue and saw a command for initiating the export manually but that resulted in an error that the exporter was undefined. Please advise.

![image](https://github.com/kakaroto/R20Exporter/assets/42616034/426d3e21-d0fc-4deb-99d1-3a22f42e833d)

**Comment by enter46** [comment]
Same Problem here. Worked fine yesterday.

**Comment by kakaroto** [comment]
Hi,
This is due to a change to the roll20 site which they did yesterday. I'll soon be releasing an update to fix it. 
In the meantime, if your Roll20 URL is `https://app.roll20.net/editor/?oauth_check=1` , remove the `?oauth_check=1` at the end of the URL, and it should work.
Your Roll20 campaign URL should be: https://app.roll20.net/editor/
